### ISSUE TITLE
Do you present the relation between events to express the temporal relationship or causal result relationship? 

### ISSUE THREAD

**Issue by dinhngoc267** [SemanticComputing/Warsampo-schema#1]
Hi, I'm so glad to find your work. Amazing work. 

As I'm working on Historical domain too, I found it's so hard to structure knowledge into graph. In my ontology, I use a lot of literal nodes to describe an event. I see your ontology has class and property. So there's no relation between events? Do you have a visualization of the whole ontology? 

And is there any application for this database? like Q.A or information retrieval. I would love to read it.

**Comment by yoge1** [comment]
Thanks for the feedback!

I think the only relation between events in the ontology and the [WarSampo dataset](https://www.ldf.fi/dataset/warsa) is the property http://ldf.fi/schema/warsa/events/related_period. The property is used for connecting events such as political activities, battles, promotions, and photographies to wars (e.g. Winter War).

The ontology and the WarSampo dataset has been described in our paper:
Mikko Koho, Esko Ikkala, Petri Leskinen, Minna Tamper, Jouni Tuominen and Eero Hyvönen: WarSampo Knowledge Graph: Finland in the Second World War as Linked Open Data. Semantic Web – Interoperability, Usability, Applicability, vol. 12, no. 2, pp. 265-278, January, 2021. DOI: [10.3233/SW-200392](https://doi.org/10.3233/SW-200392). Open access copy available: https://seco.cs.aalto.fi/publications/2021/koho-et-al-warsampo-kg.pdf

You can also investigate the ontology with [pyLODE](https://www.ldf.fi/service/pylode?url=http://ldf.fi/schema/warsa#warsa) and [WebVOWL](https://service.tib.eu/webvowl/#iri=http://ldf.fi/schema/warsa).

The WarSampo portal based on the WarSampo ontology and dataset is available at https://www.sotasampo.fi/en/
